version: '2'

services:

  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      #
      #### Plaintext Test
      #
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://127.0.0.1:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      #
      #### From (broken) example repo
      #
      # KAFKA_BROKER_ID: 1
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_ADVERTISED_HOST_NAME: localhost
      # KAFKA_LISTENERS: 'SSL://:9092'
      # KAFKA_ADVERTISED_LISTENERS: 'SSL://:9092'
      # KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_SSL_KEYSTORE_LOCATION: '/certs/docker.kafka.server.keystore.jks'
      # KAFKA_SSL_KEYSTORE_PASSWORD: 'kafkadocker'
      # KAFKA_SSL_KEY_PASSWORD: 'kafkadocker'
      # KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/docker.kafka.server.truststore.jks'
      # KAFKA_SSL_TRUSTSTORE_PASSWORD: 'kafkadocker'
      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      # KAFKA_SSL_CLIENT_AUTH: 'none'

      #
      #### With certs from working local instance ####
      #
      # KAFKA_BROKER_ID: 1
      # KAFKA_ADVERTISED_HOST_NAME: localhost
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_LISTENERS: 'SSL://:9092'
      # KAFKA_ADVERTISED_LISTENERS: 'SSL://:9092'
      # KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_SSL_KEYSTORE_LOCATION: '/ogssl/kafka.server.keystore.jks'
      # KAFKA_SSL_KEYSTORE_PASSWORD: 'test1234'
      # KAFKA_SSL_KEY_PASSWORD: 'test1234'
      # KAFKA_SSL_TRUSTSTORE_LOCATION: '/ogssl/kafka.server.truststore.jks'
      # KAFKA_SSL_TRUSTSTORE_PASSWORD: 'test1234'
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
      # KAFKA_SSL_CLIENT_AUTH: 'none'

      #
      ##### Recreation of local instance #####
      #
      # KAFKA_LISTENERS: 'SSL://localhost:9092'
      # KAFKA_ADVERTISED_LISTENERS: 'SSL://localhost:9092'
      # KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      # KAFKA_SSL_KEYSTORE_LOCATION: './ogssl/kafka.server.keystore.jks'
      # KAFKA_SSL_KEYSTORE_PASSWORD: 'test1234'
      # KAFKA_SSL_KEY_PASSWORD: 'test1234'
      # KAFKA_SSL_TRUSTSTORE_LOCATION: './ogssl/kafka.server.truststore.jks'
      # KAFKA_SSL_TRUSTSTORE_PASSWORD: 'test1234'
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
      # KAFKA_SSL_CLIENT_AUTH: 'none'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # From example
      - ./certs:/certs
      # From working local instance
      - ./ogssl:/ogssl


# /opt/kafka_2.11-0.10.1.0
# kafka-topics --zookeeper 127.0.0.1:2181 --topic kafka-pt-topic --create --partitions 1 --replication-factor 1 && kafka-console-producer --broker-list 127.0.0.1:9092 --topic kafka-pt-topic
